#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "ui_image_line_show.h"
#include "opstring.h"
#include "stockDataGet.h"
#include "QWidget"
#include "image_line_show.h"
#include "real_kline_work.h"
